export const sampleQuery = {
    view: "customers_extended",
    fields: [
        "customers._name",
        "customers.customer_id"
    ],
    pivots: null,
    fill_fields: null,
    filters: null,
    filter_expression: null,
    sorts: [
        "customers._name"
    ],
    limit: "500",
    column_limit: null,
    total: null,
    row_total: null,
    subtotals: null,
    vis_config: {
    show_view_names: false,
        show_row_numbers: true,
        transpose: false,
        truncate_text: true,
        hide_totals: false,
        hide_row_totals: false,
        size_to_fit: true,
        table_theme: "white",
        limit_displayed_rows: false,
        enable_conditional_formatting: false,
        header_text_alignment: "left",
        header_font_size: 12,
        rows_font_size: 12,
        conditional_formatting_include_totals: false,
        conditional_formatting_include_nulls: false,
        series_types: {},
        type: "looker_grid",
        defaults_version: 1
    },
    filter_config: {},
    visible_ui_sections: null,
    model: "na1_dev_base",
    dynamic_fields: "[]",
    query_timezone: null,
    quick_calcs: [],
    analysis_config: null,
    can: {
        run: true,
        see_results: true,
        explore: true,
        create: true,
        show: true,
        cost_estimate: true,
        index: true,
        see_lookml: true,
        see_aggregate_table_lookml: true,
        see_derived_table_lookml: true,
        see_sql: true,
        save: true,
        generate_drill_links: true,
        download: true,
        download_unlimited: true,
        use_custom_fields: true,
        edit_custom_fields: true,
        edit_table_calculations: true,
        schedule: true,
        render: true
    }
}
